test_only: True

data_path: "/home/alehandreus/E/Brain/CUP2/covers_detection_contest/dataset/"
batch_size: 25
num_workers: 5
epochs: 4
learning_rate: 0.0001

mae_path: null #"mae_0.179.pt"
checkpoint_path: "arc_0.627.pt"

min_clique_size: 10
rerank: True
num_classes: 39535